Resources:
  BuildTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: coa_publisher_${env:DEPLOY_ENV}
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: build_id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: build_id.janis
          KeySchema:
            - AttributeName: build_id
              KeyType: HASH
            - AttributeName: pk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      LocalSecondaryIndexes:
        - IndexName: janis.status
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE
