Resources:
  BuildTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: coa_publisher_${env:DEPLOY_ENV}
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
        - AttributeName: build_id
          AttributeType: S
        - AttributeName: state
          AttributeType: S
        - AttributeName: waiting
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: build_id
          KeySchema:
            - AttributeName: build_id
              KeyType: HASH
            - AttributeName: pk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: state
          KeySchema:
            - AttributeName: state
              KeyType: HASH
            - AttributeName: build_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      LocalSecondaryIndexes:
        - IndexName: waiting
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: waiting
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
