Conditions:
  IsProduction:
    Fn::Equals:
      - ${env:DEPLOY_ENV}
      - production
Resources:
  ProductionBucket:
    Type: AWS::S3::Bucket
    Condition: IsProduction
    DeletionPolicy: Retain
    Properties:
      BucketName: coa-janis-austin-gov-production
      WebsiteConfiguration:
        ErrorDocument: 404.html
        IndexDocument: index.html
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins: ['*']
            AllowedMethods: [GET]
            AllowedHeaders: [Content-Length]

  # TODO: code-composable production structures, following pattern of what staging has.
