service: coa-publisher

# plugins:
#   - serverless-webpack

custom:
  # webpack:
  #   webpackConfig: 'webpack.config.js'
  #   packager: 'yarn'
  #   keepOutputDirectory: true

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.14.1
  deploymentBucket:
    name: coa-publisher
  region: ${env:AWS_REGION}
  stage: ${env:DEPLOY_ENV}
  stackName: coa-publisher-${env:DEPLOY_ENV}
  stackTags:
    user:app: publisher
    user:env: ${env:DEPLOY_ENV}
    user:project: alpha.austin.gov
  vpc:
    securityGroupIds:
      - !Ref ClusterSecurityGroup
    subnetIds:
      - !Ref SubnetOnePublic
      - !Ref SubnetTwoPublic

# Many thanks to: https://github.com/nathanpeck/aws-cloudformation-fargate/blob/master/fargate-networking-stacks/public-vpc.yml
resources:
  - ${file(networking.yml)}
  - ${file(ecs.yml)}
  - ${file(logs.yml)}
  - ${file(codebuild.yml)}
