version: 0.2

env:
  variables:
    JANIS_BRANCH: ""
    JOPLIN_BRANCH: ""
    DEST: ""
    CMS_MEDIA: ""
  # These values are stored in the AWS System Manager Parameter Store
  # https://console.aws.amazon.com/systems-manager/parameters/?region=us-east-1
  parameter-store:
    DOCKER_USER: "coa_publisher_docker_user"
    DOCKER_PASS: "coa_publisher_docker_pass"

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
      - export TAG="cityofaustin/branch-publisher:$JANIS_BRANCH"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build
        -f ./branch-publisher.Dockerfile
        -t $TAG
        --build-arg JANIS_BRANCH=$JANIS_BRANCH
        --build-arg JOPLIN_BRANCH=$JOPLIN_BRANCH
        --build-arg DEST=$DEST
        --build-arg CMS_MEDIA=$CMS_MEDIA
        .
  post_build:
    commands:
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 0 ]; then exit 1; fi # Exit early if build step failed
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $TAG
