# Many thanks to: https://github.com/nathanpeck/aws-cloudformation-fargate/blob/master/fargate-networking-stacks/public-vpc.yml
service: coa-publisher

# plugins:
#   - serverless-webpack

custom:
  # webpack:
  #   webpackConfig: 'webpack.config.js'
  #   packager: 'yarn'
  #   keepOutputDirectory: true
  JanisBuilderBaseEcrName: "cityofaustin/janis_builder_base"
  JanisBuilderEcrName: "cityofaustin/janis_builder"

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.14.1
  deploymentBucket:
    name: coa-publisher
  region: ${env:AWS_REGION}
  stage: ${env:SLS_STAGE}
  stackName: coa-publisher-${env:SLS_STAGE}
  stackTags:
    user:app: publisher
    user:stage: ${env:SLS_STAGE}
    user:project: alpha.austin.gov
  vpc:
    securityGroupIds:
      - !Ref ClusterSecurityGroup
    subnetIds:
      - !Ref SubnetOnePublic
      - !Ref SubnetTwoPublic

# Many thanks to: https://github.com/nathanpeck/aws-cloudformation-fargate/blob/master/fargate-networking-stacks/public-vpc.yml
resources:
  - ${file(networking.yml)}
  - ${file(ecs.yml)}
  - ${file(logs.yml)}
  - ${file(ecr.yml)}
  - ${file(codebuild.yml)}
