version: 0.2

env:
  variables:
    JANIS_BRANCH: ""
    JOPLIN_BRANCH: ""
    DEST: ""
    CMS_MEDIA: ""
  parameter-store:
    DOCKER_USER: "DOCKER_USER"
    DOCKER_PASS: "DOCKER_PASS"

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - export TAG="cityofaustin/branch-publisher:$JANIS_BRANCH"
      - >
        docker build
          -f ./branch-publisher.Dockerfile
          -t $TAG
          --build-arg JANIS_BRANCH=$JANIS_BRANCH
          --build-arg JOPLIN_BRANCH=$JOPLIN_BRANCH
          --build-arg DEST=$DEST
          --build-arg CMS_MEDIA=$CMS_MEDIA
          .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $TAG
