Parameters:
  Env:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - prod

Resources:
  # Create a CodeBuild Project to build new branch-publisher images
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Join [ '-', [ 'coa-branch-publisher-builder', !Ref Env ] ]
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: true # Required for building docker images and LOCAL caching
      Source:
        Type: S3
        Location: !Join [ '', ['coa-publisher-codebuild/source/', !Ref Env, '/'] ]
        BuildSpec: './buildspec.yml'
      TimeoutInMinutes: 10
      Cache:
        Type: LOCAL # Caches Docker layers on AWS Host build machine
        Modes:
          - LOCAL_DOCKER_LAYER_CACHE

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'coa-publisher-codebuild'
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: AmazonECSTaskExecutionRolePolicy
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                # retrieve custom environment variables stored in Amazon EC2 Systems Manager Parameter Store
                - 'ssm:GetParameters'
                # Allow the ECS tasks to upload logs to CloudWatch
                - 'logs:*'
              Resource: '*'
            - Effect: Allow
              Action:
                # allow reading from coa-publisher-codebuild s3 bucket
                - 's3:ListBucket'
              Resource: 'arn:aws:s3:::coa-publisher-codebuild'
            - Effect: Allow
              Action:
                # allow GET/PUT for objects in coa-publisher-codebuild s3 bucket
                - 's3:GetBucketLocation'
                - 's3:GetObject'
                - 's3:DeleteObject'
                - 's3:PutObject'
              Resource: 'arn:aws:s3:::coa-publisher-codebuild/*'
